export const autoGeneratedFields = [
    'id',
    'date_created',
    'last_modified'
];

export const collectionsList = [
    'vasts',
    'keywords'
];

export const MODE_EDITING = 'EDITING';
export const MODE_CREATING = 'CREATING';